version: '3.8'
services:
  api-tracker:
    image: node:latest
    container_name: nodeapp
    restart: always
    command: yarn start
    env_file:
      - .env
    depends_on:
      - mongo-database
    build: .
    ports:
      - "3000:3000"
    networks:
      - my_network
    working_dir: /home/app
    volumes:
      - .:/home/app

  mongo-database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongo-data:/data/db
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=test

networks:
  my_network:

volumes:
  mongo-data:
